class AddVpdReferencesIndex < ActiveRecord::Migration[7.1]
  def change
    add_index :accounts,                  [:id, :vpd_id]
    add_index :posts,                     [:id, :vpd_id]
    add_index :vpd_sponsors,              [:id, :vpd_id]
    add_index :vpd_countries,             [:id, :vpd_id]
    add_index :vpd_currencies,            [:id, :vpd_id]
    add_index :vpd_mail_templates,        [:id, :vpd_id]
    add_index :vpd_approvers,             [:id, :vpd_id]
    add_index :vpd_reports,               [:id, :vpd_id]
    add_index :vpd_ledger_categories,     [:id, :vpd_id]
    add_index :vpd_events,                [:id, :vpd_id]
    add_index :trials,                    [:id, :vpd_id]
    add_index :trial_schedules,           [:id, :vpd_id]
    add_index :trial_events,              [:id, :vpd_id]
    add_index :trial_entries,             [:id, :vpd_id]
    add_index :trial_passthrough_budgets, [:id, :vpd_id]
    add_index :forecastings,              [:id, :vpd_id]
    add_index :sites,                     [:id, :vpd_id]
    add_index :site_schedules,            [:id, :vpd_id]
    add_index :site_events,               [:id, :vpd_id]
    add_index :site_entries,              [:id, :vpd_id]
    add_index :site_passthrough_budgets,  [:id, :vpd_id]
    add_index :passthroughs,              [:id, :vpd_id]
    add_index :invoices,                  [:id, :vpd_id]
    add_index :transactions,              [:id, :vpd_id]
  end
end
